// <auto-generated />
namespace Pointwise.SqlDataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MadePubDateNullableInArticleEntity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MadePubDateNullableInArticleEntity));
        
        string IMigrationMetadata.Id
        {
            get { return "202003032047071_MadePubDateNullableInArticleEntity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
